services:
  db:
    image: mysql:8
    container_name: wordpress_db
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpsecret

  wordpress:
    image: wordpress:latest
    container_name: wordpress_app
    restart: unless-stopped

    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpsecret

    ports:
      - "8080:80"

    depends_on:
      - db